### ISSUE TITLE
ModuleNotFoundError: No module named 'helpers'

### ISSUE THREAD

**Issue by Trway** [HelixNGC7293/DeforumStableDiffusionLocal#13]
i got an error when i run python run.py --settings "./examples/runSettings_StillImages.txt"

models_path: ./models output_path: ./output Traceback (most recent call last): File "run.py", line 1312, in <module> main() File "run.py", line 112, in main from helpers import DepthModel, sampler_fn ModuleNotFoundError: No module named 'helpers'

Do you have an idea? Thanks

**Comment by vassrolandart** [comment]
I get a similar error when running python run.py --enable_animation_mode --settings "./runSettings_Template.txt"

Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 74, in main
    import IPython
ModuleNotFoundError: No module named 'IPython'

So I tought about installing IPython but Requirement already satisfied, now I'm stuck. Bumping thread!

**Comment by Trway** [comment]
> I get a similar error when running python run.py --enable_animation_mode --settings "./runSettings_Template.txt"
> 
> Traceback (most recent call last): File "run.py", line 1312, in main() File "run.py", line 74, in main import IPython ModuleNotFoundError: No module named 'IPython'
> 
> So I tought about installing IPython but Requirement already satisfied, now I'm stuck. Bumping thread!

do you know helpers come from where? thanks

**Comment by vassrolandart** [comment]
> > I get a similar error when running python run.py --enable_animation_mode --settings "./runSettings_Template.txt"
> > Traceback (most recent call last): File "run.py", line 1312, in main() File "run.py", line 74, in main import IPython ModuleNotFoundError: No module named 'IPython'
> > So I tought about installing IPython but Requirement already satisfied, now I'm stuck. Bumping thread!
> 
> do you know helpers come from where? thanks

you probably forgot to run: python setup.py
I followed a tutorial that didn't include that step, hope it helps! It should fix all nomodule errors
