### ISSUE TITLE
 free variable 'device' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by ramsesisaid** [HelixNGC7293/DeforumStableDiffusionLocal#14]
Hello sorry to bother you with this.
I can make it run on my PC

(ldm) C:\aivids\DeforumStableDiffusionLocal-main>python run.py --enable_animation_mode --settings "./examples/runSettings_Animation.txt"
Local Path Variables:

models_path: ./models
output_path: ./output
Using config: ./stable-diffusion/configs/stable-diffusion/v1-inference.yaml
Please download model checkpoint and place in ./models\sd-v1-4.ckpt
Saving animation frames to ./output\2022-09\Example_DGSpitzer
Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 1250, in main
    render_animation(args, anim_args)
  File "run.py", line 953, in render_animation
    depth_model = DepthModel(device)
NameError: free variable 'device' referenced before assignment in enclosing scope <===== THIS

THIS IS THE TEMPLATE FILE

{
    "batch_name":"Example_DGSpitzer",
    "n_batch": 1,
    "prompts":[],
    "width":512,
    "height":512,
    "seed":3521683325,
    "seed_behavior":"iter",
    "sampler":"klms",
    "steps":50,
    "scale":7,
    "ddim_eta":0.0,
    "filename_format":"{timestring}_{index}_{prompt}.png",
    "use_init":false,
    "init_image":"",
    "strength":0.0,
    "use_mask":false,
    "use_alpha_as_mask":false,
    "invert_mask":false,
    "mask_file":"",
    "animation_prompts":{
	"0":"full body portrait of a woman with short wavy hair, round face, cottagecore!!, lake water, intricate, enlightenment, highly detailed, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha",
	"10":"beautiful amazing alien landscape with lush vegetation and colourful galaxy foreground, digital art, breathtaking, golden ratio, extremely detailed, hyper - detailed, establishing shot, hyperrealistic, cinematic lighting, particles, unreal engine, simon stalenhag, rendered by beeple, makoto shinkai, syd meade, kentaro miura, jean giraud, environment concept, artstation, octane render, 8k uhd image",
	"20":"beautiful desolate city fill with giant flowers, moody :: by James Jean, Jeff Koons, Dan McPharlin Daniel Merrian :: ornate, dynamic, particulate, rich colors, intricate, elegant, highly detailed, centered, artstation, smooth, sharp focus, octane render, 3d"
    },
    "animation_mode":"3D",
    "max_frames":30,
    "diffusion_cadence":"3",
    "border":"warp",
    "angle":"0:(0)",
    "zoom":"0:(1.04)",
    "translation_x":"0:(0)",
    "translation_y":"0:(0.5)",
    "translation_z":"0:(0.5)",
    "rotation_3d_x":"0:(0)",
    "rotation_3d_y":"0:(0)",
    "rotation_3d_z":"0:(0)",
    "noise_schedule":"0:(0.02)",
    "strength_schedule":"0:(0.65)",
    "contrast_schedule":"0:(1.0)",
    "color_coherence":"Match Frame 0 LAB",
    "use_depth_warping":true,
    "midas_weight":0.3,
    "near_plane":200,
    "far_plane":10000,
    "fov":40,
    "padding_mode":"border",
    "sampling_mode":"bicubic",
    "save_depth_maps":false,
    "video_init_path":"./input/video_in.mp4",
    "extract_nth_frame":1,
    "interpolate_key_frames":true,
    "interpolate_x_frames":100,
    "resume_from_timestring":false,
    "resume_timestring":"20220829210106"
}

**Comment by sqletor420** [comment]
Please download model checkpoint and place in ./models\sd-v1-4.ckpt  <------ Looks like you need the sd-v1-4.ckpt

**Comment by Trway** [comment]
> Hello sorry to bother you with this. I can make it run on my PC
> 
> (ldm) C:\aivids\DeforumStableDiffusionLocal-main>python run.py --enable_animation_mode --settings "./examples/runSettings_Animation.txt" Local Path Variables:
> 
> models_path: ./models output_path: ./output Using config: ./stable-diffusion/configs/stable-diffusion/v1-inference.yaml Please download model checkpoint and place in ./models\sd-v1-4.ckpt Saving animation frames to ./output\2022-09\Example_DGSpitzer Traceback (most recent call last): File "run.py", line 1312, in main() File "run.py", line 1250, in main render_animation(args, anim_args) File "run.py", line 953, in render_animation depth_model = DepthModel(device) NameError: free variable 'device' referenced before assignment in enclosing scope <===== THIS
> 
> The same is happening in collab
> 
> NameError Traceback (most recent call last) in 480 # dispatch to appropriate renderer 481 if anim_args.animation_mode == '2D' or anim_args.animation_mode == '3D': --> 482 render_animation(args, anim_args) 483 elif anim_args.animation_mode == 'Video Input': 484 render_input_video(args, anim_args)
> 
> in render_animation(args, anim_args) 185 predict_depths = (anim_args.animation_mode == '3D' and anim_args.use_depth_warping) or anim_args.save_depth_maps 186 if predict_depths: --> 187 depth_model = DepthModel(device) 188 depth_model.load_midas(models_path) 189 if anim_args.midas_weight < 1.0:
> 
> NameError: name 'device' is not defined <=====THIS

Do you know from helpers import DepthModel come from where? thanks

**Comment by ramsesisaid** [comment]
> Please download model checkpoint and place in ./models\sd-v1-4.ckpt <------ Looks like you need the sd-v1-4.ckpt

I already have it there. in colab

![image](https://user-images.githubusercontent.com/35149721/191749812-c8f41405-212e-4e46-bca6-f9f94a5ef9bf.png)

**Comment by afrofail** [comment]
I'm having the same issue, have you found a resolve?
