### ISSUE TITLE
Using animation_mode : video_input error

### ISSUE THREAD

**Issue by centrdev** [HelixNGC7293/DeforumStableDiffusionLocal#24]
Hey, im trying to use a video_input.
I have the config setup and the video_in.mp4 in the /input directory.

but im getting this error:

Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 1304, in main
    raise RuntimeError(stderr)
RuntimeError: b"ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers\r\n  built with gcc 10.2.1 (GCC) 20200726\r\n  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf\r\n  libavutil      56. 51.100 / 56. 51.100\r\n  libavcodec     58. 91.100 / 58. 91.100\r\n  libavformat    58. 45.100 / 58. 45.100\r\n  libavdevice    58. 10.100 / 58. 10.100\r\n  libavfilter     7. 85.100 /  7. 85.100\r\n  libswscale      5.  7.100 /  5.  7.100\r\n  libswresample   3.  7.100 /  3.  7.100\r\n  libpostproc    55.  7.100 / 55.  7.100\r\n[image2 @ 000001fef47561c0] Could find no file with path './output\\2022-09\\my_videotest2\\20220928143935_%05d.png' and index in the range 0-4\r\n./output\\2022-09\\my_videotest2\\20220928143935_%05d.png: No such file or directory\r\n"

seems like it is complaining about the missing png file... 

any suggestions on how to resolve this?

**Comment by centrdev** [comment]
this is my config:

`{
    "batch_name":"my_videotest2",
    "n_batch": 1,
    "prompts":[],
    "width":640,
    "height":320,
    "seed":2314612995,
    "seed_behavior":"iter",
    "sampler":"klms",
    "steps":50,
    "scale":5,
    "ddim_eta":0.0,
    "filename_format":"{timestring}_{index}_{prompt}.png",
    "use_init":false,
    "init_image":"./input/init_img.png",
    "strength":0.7,
    "use_mask":false,
    "use_alpha_as_mask":false,
    "invert_mask":false,
    "mask_file":"",
    "animation_prompts":{
	"0":"intricate, elegant, highly detailed. trending on artstation, digital art by artgerm, julie bell, Slawomir Maniak, james jean, marc simonetti. background by james jean"
    },
    "animation_mode":"video_input",
    "max_frames":300,
    "diffusion_cadence":"1",
    "border":"warp",
    "angle":"0:(0)",
    "zoom":"0:(1.04)",
    "translation_x":"0:(0)",
    "translation_y":"0:(0.5)",
    "translation_z":"0:(0.5)",
    "rotation_3d_x":"0:(0)",
    "rotation_3d_y":"0:(0)",
    "rotation_3d_z":"0:(0)",
    "noise_schedule":"0:(0.02)",
    "strength_schedule":"0:(0.65)",
    "contrast_schedule":"0:(1.0)",
    "color_coherence":"Match Frame 0 LAB",
    "use_depth_warping":true,
    "midas_weight":0.3,
    "near_plane":200,
    "far_plane":10000,
    "fov":40,
    "padding_mode":"border",
    "sampling_mode":"bicubic",
    "save_depth_maps":false,
    "video_init_path":"./input/video_in.mp4",
    "extract_nth_frame":1,
    "interpolate_key_frames":false,
    "interpolate_x_frames":4,
    "resume_from_timestring":false,
    "resume_timestring":"20220829210106"
}`

**Comment by centrdev** [comment]
solved thanks to https://github.com/HelixNGC7293/DeforumStableDiffusionLocal/issues/16
