### ISSUE TITLE
hash not correct error

### ISSUE THREAD

**Issue by johne5s** [HelixNGC7293/DeforumStableDiffusionLocal#27]
Any idea what might be causing this error?

(dsd) E:\DeforumStableDiffusionLocal-main>python run.py --enable_animation_mode --settings "./runSettings_Template.txt"
Local Path Variables:

models_path: ./models
output_path: ./output
Using config: ./stable-diffusion/configs/stable-diffusion/v1-inference.yaml
./models\sd-v1-4.ckpt exists

...checking sha256
hash in not correct

Saving animation frames to ./output\2022-09\TaskName
Traceback (most recent call last):
  File "run.py", line 1312, in <module>
    main()
  File "run.py", line 1250, in main
    render_animation(args, anim_args)
  File "run.py", line 953, in render_animation
    depth_model = DepthModel(device)
NameError: free variable 'device' referenced before assignment in enclosing scope

**Comment by palexpereira** [comment]
I had the same error and fixed it by going into run.py and change this line:
check_sha256= True 
to 
check_sha256= False

**Comment by johne5s** [comment]
Thank you,  Changing that to false has fixed it.
