### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by jonathanjosephb** [HelixNGC7293/DeforumStableDiffusionLocal#32]
![screen](https://user-images.githubusercontent.com/115687894/195883958-1b2a97be-e35e-4b91-822b-b7b4aa5e242a.JPG)

this is the error I recieved:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
daal4py 2021.5.0 requires daal==2021.4.0, which is not installed.
scipy 1.7.3 requires numpy<1.23.0,>=1.16.5, but you have numpy 1.23.4 which is incompatible.
numba 0.55.1 requires numpy<1.22,>=1.18, but you have numpy 1.23.4 which is incompatible.
Cloning into 'k-diffusion'...
remote: Enumerating objects: 427, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (22/22), done.
Receiving objects:  90% (385/427)used 124 (delta 124), pack-reused 281 eceiving objects:  89% (381/427)
Receiving objects: 100% (427/427), 76.34 KiB | 473.00 KiB/s, done.
Resolving deltas: 100% (286/286), done.

Environment set up in 21847 seconds

(base) C:\Users\mayab\DeforumStableDiffusionLocal-main>python run.py --enable_animation_mode --settings "./runSettings_Template.txt"
Local Path Variables:

models_path: ./models
output_path: ./output
Traceback (most recent call last):
  File "C:\Users\mayab\DeforumStableDiffusionLocal-main\run.py", line 1312, in <module>
    main()
  File "C:\Users\mayab\DeforumStableDiffusionLocal-main\run.py", line 79, in main
    import cv2
ModuleNotFoundError: No module named 'cv2'

(base) C:\Users\mayab\DeforumStableDiffusionLocal-main>

**Comment by HelixNGC7293** [comment]
It seems like the opencv is not installed, you can try to manually run this command `conda install -c conda-forge opencv -y`
Can you try the latest version's setup.py to see if that's working now?

Environment set up taking 21847 seconds definitely not normal, you may encounter some internet issue. That downloading speed is just too slow and probably it will corrupt the downloaded installation files.
