### ISSUE TITLE
ModuleNotFoundError: No module named 'IPython'

### ISSUE THREAD

**Issue by EKAPPPAEKAPPA** [HelixNGC7293/DeforumStableDiffusionLocal#37]
Hllo, im trying to start it and im getting this error... 

`C:\Users\trixs\Desktop\DeforumStableDiffusionLocal-main>python run.py --enable_animation_mode --settings "./runSettings_Template.txt"
Local Path Variables:

models_path: ./models
output_path: ./output
Traceback (most recent call last):
  File "C:\Users\trixs\Desktop\DeforumStableDiffusionLocal-main\run.py", line 1312, in <module>
    main()
  File "C:\Users\trixs\Desktop\DeforumStableDiffusionLocal-main\run.py", line 74, in main
    import IPython
ModuleNotFoundError: No module named 'IPython'`

**Comment by kingNgutor** [comment]
Are you running native or conda?
