### ISSUE TITLE
ldm and dlib are missing from the setup.

### ISSUE THREAD

**Issue by Daniel-w3** [HelixNGC7293/DeforumStableDiffusionLocal#47]
After following the setup instructions and trying to run it with bat. 
gave me error that ldm was missing, checked anaconda and it was not inside the env.
did `pip install ldm` this added the classes but ldm.py has prints without () error. Added all the brackets for all the print methods.
After this it gave me the error that dlib is missing `pip install dlib` didn't work giving install error.

Anyone else run into this issues or has anyone run the setup successfully?

**Comment by HelixNGC7293** [comment]
I didn't test it with .bat though. You can try directly run "python setup.py" using Anaconda Prompt instead of making a bat file, in Anaconda Prompt it automatically know commands like "activate" etc. so there will be no missing/skip steps during running setup.py. For ldm it doesn't need to be installed, the ldm script is inside /deforum-stable-diffusion/src/ldm folder. In setup.py line 36 there is a piece of code to add the directory to the ldm folder into this project's launching path so all the code after it can recognize and read ldm folder during import:
sys.path.extend([
        'deforum-stable-diffusion/',
        'deforum-stable-diffusion/src',
    ])

**Comment by Daniel-w3** [comment]
I am running run.py in bat only. The setup in anaconda.

**Comment by seekuu** [comment]
> I am running run.py in bat only. The setup is in anaconda.
> 
> Deleted the env and started the setup from scratch again. Still having issue with the setup.
> 
> Here is the whole thing I am running from anaconda terminal
> 
> ```
> (base) C:\Users\w2lf>cd /d D:\SD\StableDiffusion-Deforum-master
> 
> (base) D:\SD\StableDiffusion-Deforum-master>conda create --name dsd python=3.10.6 -y
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 22.9.0
>   latest version: 22.11.1
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: E:\Programs\anaconda3\envs\dsd
> 
>   added / updated specs:
>     - python=3.10.6
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0 None
>   ca-certificates    pkgs/main/win-64::ca-certificates-2022.10.11-haa95532_0 None
>   certifi            pkgs/main/win-64::certifi-2022.12.7-py310haa95532_0 None
>   libffi             pkgs/main/win-64::libffi-3.4.2-hd77b12b_6 None
>   openssl            pkgs/main/win-64::openssl-1.1.1s-h2bbff1b_0 None
>   pip                pkgs/main/win-64::pip-22.3.1-py310haa95532_0 None
>   python             pkgs/main/win-64::python-3.10.6-hbb2ffb3_1 None
>   setuptools         pkgs/main/win-64::setuptools-65.5.0-py310haa95532_0 None
>   sqlite             pkgs/main/win-64::sqlite-3.40.0-h2bbff1b_0 None
>   tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0 None
>   tzdata             pkgs/main/noarch::tzdata-2022g-h04d1e81_0 None
>   vc                 pkgs/main/win-64::vc-14.2-h21ff451_1 None
>   vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2 None
>   wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0 None
>   wincertstore       pkgs/main/win-64::wincertstore-0.2-py310haa95532_2 None
>   xz                 pkgs/main/win-64::xz-5.2.8-h8cc25b3_0 None
>   zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0 None
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> #
> # To activate this environment, use
> #
> #     $ conda activate dsd
> #
> # To deactivate an active environment, use
> #
> #     $ conda deactivate
> 
> Retrieving notices: ...working... done
> 
> (base) D:\SD\StableDiffusion-Deforum-master>conda activate dsd
> 
> (dsd) D:\SD\StableDiffusion-Deforum-master>cd /d D:\SD\StableDiffusion-Deforum-master
> 
> (dsd) D:\SD\StableDiffusion-Deforum-master>python setup.py
> Setting up environment...
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 22.9.0
>   latest version: 22.11.1
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: E:\Programs\anaconda3\envs\dsd
> 
>   added / updated specs:
>     - git
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   git                pkgs/main/win-64::git-2.34.1-haa95532_0 None
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Retrieving notices: ...working... done
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 22.9.0
>   latest version: 22.11.1
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: E:\Programs\anaconda3\envs\dsd
> 
>   added / updated specs:
>     - opencv
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   eigen              conda-forge/win-64::eigen-3.4.0-h2d74725_0 None
>   glib               pkgs/main/win-64::glib-2.69.1-h5dc1a3c_2 None
>   gst-plugins-base   pkgs/main/win-64::gst-plugins-base-1.18.5-h9e645db_0 None
>   gstreamer          pkgs/main/win-64::gstreamer-1.18.5-hd78058f_0 None
>   hdf5               conda-forge/win-64::hdf5-1.10.6-nompi_he0bbb20_101 None
>   icu                pkgs/main/win-64::icu-58.2-ha925a31_3 None
>   intel-openmp       conda-forge/win-64::intel-openmp-2023.0.0-h57928b3_25922 None
>   jpeg               conda-forge/win-64::jpeg-9e-h8ffe710_2 None
>   libblas            conda-forge/win-64::libblas-3.9.0-8_mkl None
>   libcblas           conda-forge/win-64::libcblas-3.9.0-8_mkl None
>   libclang           pkgs/main/win-64::libclang-12.0.0-default_h627e005_2 None
>   libiconv           conda-forge/win-64::libiconv-1.17-h8ffe710_0 None
>   liblapack          conda-forge/win-64::liblapack-3.9.0-8_mkl None
>   libogg             conda-forge/win-64::libogg-1.3.4-h8ffe710_1 None
>   libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0 None
>   libprotobuf        pkgs/main/win-64::libprotobuf-3.20.1-h23ce68f_0 None
>   libtiff            conda-forge/win-64::libtiff-4.0.9-h36446d0_1002 None
>   libvorbis          conda-forge/win-64::libvorbis-1.3.7-h0e60522_0 None
>   libwebp            conda-forge/win-64::libwebp-1.2.4-h8ffe710_0 None
>   libwebp-base       conda-forge/win-64::libwebp-base-1.2.4-h8ffe710_0 None
>   libxml2            pkgs/main/win-64::libxml2-2.9.14-h0ad7f3c_0 None
>   libxslt            pkgs/main/win-64::libxslt-1.1.35-h2bbff1b_0 None
>   lz4-c              conda-forge/win-64::lz4-c-1.9.3-h8ffe710_1 None
>   mkl                conda-forge/win-64::mkl-2020.4-hb70f87d_311 None
>   numpy              conda-forge/win-64::numpy-1.22.4-py310hed7ac4c_0 None
>   opencv             pkgs/main/win-64::opencv-4.6.0-py310ha7641e4_2 None
>   pcre               conda-forge/win-64::pcre-8.45-h0e60522_0 None
>   python_abi         conda-forge/win-64::python_abi-3.10-2_cp310 None
>   qt-main            pkgs/main/win-64::qt-main-5.15.2-he8e5bd7_7 None
>   qt-webengine       pkgs/main/win-64::qt-webengine-5.15.9-hb9a9bb5_4 None
>   qtwebkit           pkgs/main/win-64::qtwebkit-5.212-h3ad3cdb_4 None
>   zstd               pkgs/main/win-64::zstd-1.5.2-h19a0ad4_0 None
> 
> The following packages will be UPDATED:
> 
>   ca-certificates    pkgs/main::ca-certificates-2022.10.11~ --> conda-forge::ca-certificates-2022.12.7-h5b45459_0 None
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
>   certifi            pkgs/main/win-64::certifi-2022.12.7-p~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0 None
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Retrieving notices: ...working... done
> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 22.9.0
>   latest version: 22.11.1
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: E:\Programs\anaconda3\envs\dsd
> 
>   added / updated specs:
>     - ffmpeg
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   ffmpeg             conda-forge/win-64::ffmpeg-4.3.1-ha925a31_0 None
> 
> 
> Preparing transaction: done
> Verifying transaction: done
> Executing transaction: done
> Retrieving notices: ...working... done
> Setting up environment part2...
> ..installing xformers
> NVIDIA GeForce RTX 2060
>  Searching xformers flash attention wheel file for deforum!
> mv: cannot stat 'deforum-stable-diffusion/src/ldm/modules/attention.py': No such file or directory
> mv: cannot stat 'deforum-stable-diffusion/src/ldm/modules/attention_xformers.py': No such file or directory
> Environment set up in 341 seconds
> 
> (dsd) D:\SD\StableDiffusion-Deforum-master>python run.py --enable_animation_mode --settings "./runSettings_Template.txt" --model "v1-5-pruned-emaonly.ckpt"
> models_path: D:\SD\StableDiffusion-Deforum-master\models
> output_path: D:\SD\StableDiffusion-Deforum-master\output
> configs\v1-inference.yaml exists
> config_path: D:\SD\StableDiffusion-Deforum-master\configs\v1-inference.yaml
> ckpt_path: D:\SD\StableDiffusion-Deforum-master\models\v1-5-pruned-emaonly.ckpt
> ..loading model
> Traceback (most recent call last):
>   File "D:\SD\StableDiffusion-Deforum-master\run.py", line 458, in <module>
>     main()
>   File "D:\SD\StableDiffusion-Deforum-master\run.py", line 96, in main
>     root.model, root.device = load_model(root,
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion\helpers\model_load.py", line 213, in load_model
>     model = load_model_from_config(local_config, f"{ckpt_path}", half_precision=root.half_precision)
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion\helpers\model_load.py", line 194, in load_model_from_config
>     model = instantiate_from_config(config.model)
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion/src\ldm\util.py", line 85, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()))
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion/src\ldm\util.py", line 93, in get_obj_from_str
>     return getattr(importlib.import_module(module, package=None), cls)
>   File "E:\Programs\anaconda3\envs\dsd\lib\importlib\__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion/src\ldm\models\diffusion\ddpm.py", line 25, in <module>
>     from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion/src\ldm\models\autoencoder.py", line 8, in <module>
>     from ldm.modules.diffusionmodules.model import Encoder, Decoder
>   File "D:\SD\StableDiffusion-Deforum-master\deforum-stable-diffusion/src\ldm\modules\diffusionmodules\model.py", line 10, in <module>
>     from ldm.modules.attention import LinearAttention
> ModuleNotFoundError: No module named 'ldm.modules.attention'
> 
> (dsd) D:\SD\StableDiffusion-Deforum-master>
> ```

Hello! Were you able to solve the problem?

**Comment by mdolnik** [comment]
> I then ran into TONS of other problems, like with trying to get ldm to work. There is something seriously wrong when you're stuck in this level of dependency hell!

I'm not sure if you ever got it to work or not, I ended up getting to the same situation as you.

Regardless, I gave up and ended up having success with the `0.4` version of this repo. I forget what other packages I had to manually install (basically I ran `pip install NAME` for every error I got), but it didn't involve any editing of package code to fix the print issue.

Note: The 0.4 version readme instructions has you download different model files (and 0.4 has `AdaBins_nyu.pt` in the `pretrained` folder).
