### ISSUE TITLE
Error "compute_indices_weights_cubic" not implemented for 'Half'

### ISSUE THREAD

**Issue by ghost** [HelixNGC7293/DeforumStableDiffusionLocal#58]
Using Deforum on Mac M1 and getting this error

that's what i see in terminal:

*START OF TRACEBACK*
Traceback (most recent call last):
  File "/Users/tikachov/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py", line 109, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "/Users/tikachov/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/render.py", line 301, in render_animation
    depth = depth_model.predict(turbo_next_image, anim_args.midas_weight, root.half_precision)
  File "/Users/tikachov/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/depth.py", line 104, in predict
    midas_depth = torch.nn.functional.interpolate(
  File "/Users/tikachov/stable-diffusion-webui/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 3967, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_indices_weights_cubic" not implemented for 'Half'
*END OF TRACEBACK*

User friendly error message:
Error: "compute_indices_weights_cubic" not implemented for 'Half'. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \.
Deforum progress:   0%|                        | 1/1192 [00:02<55:53,  2.82s/it]

**Comment by chessboy** [comment]
running into the same issue on M2max MBP... any ideas on this?
